$(document).ready(function(){
    $("#INDsecond1").click(function(){
      $("#INDsecond1sp").fadeToggle(1000);
    });
    $("#INDsecond1d").click(function(){
      $("#INDsecond1sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#INDsecond2").click(function(){
      $("#INDsecond2sp").fadeToggle(1000);
    });
    $("#INDsecond2d").click(function(){
      $("#INDsecond2sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#INDsecond3").click(function(){
      $("#INDsecond3sp").fadeToggle(1000);
    });
    $("#INDsecond3d").click(function(){
      $("#INDsecond3sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#INDsecond4").click(function(){
      $("#INDsecond4sp").fadeToggle(1000);
    });
    $("#INDsecond4d").click(function(){
      $("#INDsecond4sp").fadeToggle(1000);
    });
});