$(document).ready(function(){
    $("#sixth1").click(function(){
      $("#sixth1sp").fadeToggle(1000);
    });
    $("#sixth1d").click(function(){
      $("#sixth1sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#sixth2").click(function(){
      $("#sixth2sp").fadeToggle(1000);
    });
    $("#sixth2d").click(function(){
      $("#sixth2sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#sixth3").click(function(){
      $("#sixth3sp").fadeToggle(1000);
    });
    $("#sixth3d").click(function(){
      $("#sixth3sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#sixth4").click(function(){
      $("#sixth4sp").fadeToggle(1000);
    });
    $("#sixth4d").click(function(){
      $("#sixth4sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#sixth5").click(function(){
      $("#sixth5sp").fadeToggle(1000);
    });
    $("#sixth5d").click(function(){
      $("#sixth5sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#sixth6").click(function(){
      $("#sixth6sp").fadeToggle(1000);
    });
    $("#sixth6d").click(function(){
      $("#sixth6sp").fadeToggle(1000);
    });
});