$(document).ready(function(){
    $("#zero1").click(function(){
      $("#zero1sp").fadeToggle(1000);
    });
    $("#zero1d").click(function(){
      $("#zero1sp").fadeToggle(1000);
    });
});
$(document).ready(function(){
    $("#zero2").click(function(){
      $("#zero2sp").fadeToggle(1000);
    });
    $("#zero2d").click(function(){
      $("#zero2sp").fadeToggle(1000);
    });
  });
$(document).ready(function(){
    $("#zero3").click(function(){
      $("#zero3sp").fadeToggle(1000);
    });
    $("#zero3d").click(function(){
      $("#zero3sp").fadeToggle(1000);
    });
  });
$(document).ready(function(){
    $("#zero4").click(function(){
      $("#zero4sp").fadeToggle(1000);
    });
    $("#zero4d").click(function(){
      $("#zero4sp").fadeToggle(1000);
    });
  });
$(document).ready(function(){
    $("#zero5").click(function(){
      $("#zero5sp").fadeToggle(1000);
    });
    $("#zero5d").click(function(){
      $("#zero5sp").fadeToggle(1000);
    });
  });
$(document).ready(function(){
    $("#zero6").click(function(){
      $("#zero6sp").fadeToggle(1000);
    });
    $("#zero6d").click(function(){
      $("#zero6sp").fadeToggle(1000);
    });
  });